### ISSUE TITLE
Error after moving the point and clicking

### ISSUE THREAD

**Issue by Saramud** [ppete2/Leaflet.PolylineMeasure#104] opened 2023-04-21 10:09 UTC
Hello!

I found a problem when I click on a point and drag it and click on the right place again.  The 'this._tooltip' object in the '_addFocusListenersOnLayer' method is empty for some reason. This can also be played on a demo (https://ppete2.github.io/Leaflet.PolylineMeasure/demo1.html)

Uncaught TypeError: Cannot set properties of null (setting '_source')
![image](https://user-images.githubusercontent.com/43354550/233608731-3872c5ea-e317-48f7-ac64-d3592909685f.png)

**Comment by ppete2** [comment] 2023-06-21 09:18
Please explain in detail, step by step what you are doing to get this problem, thanks.

**Comment by Saramud** [comment] 2023-06-23 09:31
1. Start draw
2. Click to finish line
3. Then click and drag to move point
![PolylineMeasure](https://github.com/ppete2/Leaflet.PolylineMeasure/assets/43354550/0128fdff-4076-4a5c-846e-2234a3fd50f8)

**Comment by ppete2** [comment] 2023-06-23 10:09
Strange, I cannot reproduce this bug, neither with Firefox nor with Chrome.
Are you using the latest version of the Plugin? e.g. https://ppete2.github.io/Leaflet.PolylineMeasure/demo2.html

**Comment by Saramud** [comment] 2023-06-23 10:26
I reproduced this issue on OS Ubuntu 24.04, chrome (v.114.0.5735.134 (64b)). Used this demo https://ppete2.github.io/Leaflet.PolylineMeasure/demo2.html. Not a problem in Firefox.

**Comment by ppete2** [comment] 2023-06-23 10:33
Is this bug negative affecting the plugins' function - aside from the console-log? I'm not even sure if this is a plugin-related problem or something to do with Leaflet or Chrome for Linux in general.
Since I don't use Linux or Ubuntu I'm not able to solve this one, sorry.

**Comment by Saramud** [comment] 2023-06-23 10:36
I was able to reproduce on win10 too.
Okay, thank you.

**Comment by ppete2** [comment] 2023-06-23 10:38
And with Win10 - Edge Browser?

**Comment by Saramud** [comment] 2023-06-23 10:44
Yes, I just checked on edge, the same problem

**Comment by ppete2** [comment] 2023-06-23 10:47
Do you have a friend with another PC, running Win10-Chrome to check if it's just a problem on your PC?

**Comment by Saramud** [comment] 2023-06-23 10:50
Before posting the problem I checked on different computers.

пт, 23 июн. 2023 г. в 13:47, PPete ***@***.***>:

**Comment by ppete2** [comment] 2023-06-23 10:55
I'm sorry but I've to close this issue cause I'm not able to reproduce or to solve this message. I'm not even sure if it's cause is within this plugin. I hope it doesn't negative impact the work with the plugin, otherwise you have to avoid moving points.

**Comment by Saramud** [comment] 2023-06-23 10:56
Thank you.

**Closed** 2023-06-23 11:01 UTC
